import sys

with open('src/pages/HomePage.jsx', 'r', encoding='utf-8') as f:
    content = f.read()
    
with open('hero_replacement.txt', 'r', encoding='utf-8') as f:
    hero = f.read()

# 1. Apply Hero Replacement
start_marker = '{/* HERO SECTION */}'
end_marker = '{/* FEATURES */}'
start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx != -1 and end_idx != -1:
    content = content[:start_idx] + hero + '\n        ' + content[end_idx:]

# 2. Fix useAuth destructuring
content = content.replace('const { isAuthenticated } = useAuth();', 'const { isAuthenticated, user } = useAuth();')

# 3. Add BottomNav import
content = content.replace(
    "import { Navbar } from '@/components/navigation/Navbar';",
    "import { Navbar } from '@/components/navigation/Navbar';\nimport { BottomNav } from '@/components/layout/BottomNav';"
)

# 4. Add Frosted Edges & BottomNav
edges = '''        {/* Native-feeling static frosted glass edges */}
        <div className="fixed top-0 left-0 right-0 h-[calc(10px+env(safe-area-inset-top))] z-[60] backdrop-blur-sm bg-gradient-to-b from-[#030712]/90 to-transparent pointer-events-none" />
        <div className="fixed bottom-0 left-0 right-0 h-[calc(10px+env(safe-area-inset-bottom))] z-[60] backdrop-blur-sm bg-gradient-to-t from-[#030712]/90 to-transparent pointer-events-none" />

        <Navbar />
        {isAuthenticated && <BottomNav />}'''
content = content.replace('<Navbar />', edges)

# 5. Fix syntax errors generated by hero_replacement
content = content.replace('"{', '={${glassStyle}')
content = content.replace('"{', '={${glassPill}')
content = content.replace('}"', '}')
content = content.replace('}>', '}>')
content = content.replace('className=={', 'className={')

# 6. Apply Compact Layout Changes
# a) Update main spacing
main_old = '<main className="relative z-10 w-full max-w-[1440px] mx-auto px-4 sm:px-8 lg:px-12 pt-32 sm:pt-36 lg:pt-48">'
main_new = '<main className={elative z-10 w-full max-w-[1440px] mx-auto px-4 sm:px-8 lg:px-12 }>'
content = content.replace(main_old, main_new)

# b) Update section spacing
section_old = '<section className="relative min-h-[70vh] lg:min-h-[90vh] flex flex-col justify-center pb-10 lg:pb-20">'
section_new = '<section className={elative flex flex-col justify-center pb-10 lg:pb-20 }>'
content = content.replace(section_old, section_new)

# c) Fix Welcome message Name
old_welcome = "Welcome back, <br className=\"hidden lg:block\"/> <span className=\"text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400\">{user?.name?.split(' ')[0] || 'Traveler'}</span>."
new_welcome = "Welcome back, <br className=\"hidden lg:block\"/> <span className=\"text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400\">{user?.displayName?.split(' ')[0] || user?.name?.split(' ')[0] || 'Traveler'}</span>."
content = content.replace(old_welcome, new_welcome)

# d) Fix Welcome text size
old_size = "text-4xl sm:text-6xl lg:text-[72px] font-semibold tracking-tighter leading-[1.05]"
new_size = "text-4xl sm:text-5xl lg:text-[60px] font-semibold tracking-tighter leading-tight break-words max-w-full"
content = content.replace(old_size, new_size)

# e) Remove Quick Links
quick_links_start = '{/* Quick Links Row */}'
quick_links_end = '</motion.div>'
q_start = content.find(quick_links_start)
if q_start != -1:
    # Find the closing motion.div for the quick links
    q_end = content.find(quick_links_end, q_start) + len(quick_links_end)
    content = content[:q_start] + content[q_end:]

# f) Replace Ticket Widget with New Compact Hero Image version
ticket_start_str = '{/* Authenticated Dashboard: Right Side Ticket Widget */}'
ticket_start = content.find(ticket_start_str)
ticket_end_str = '{/* Decorative blur blobs behind ticket */}'
ticket_end = content.find(ticket_end_str)

if ticket_start != -1 and ticket_end != -1:
    new_ticket = '''{/* Authenticated Dashboard: Right Side Ticket Widget */}
              <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8 }} className="lg:col-span-6 w-full relative order-2 mt-2 sm:mt-6 lg:mt-0 flex items-center justify-center perspective-[1200px] px-2 sm:px-0">
                <motion.div 
                   animate={{ y: [-3, 3, -3] }} 
                   transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}
                   className="w-full max-w-sm relative z-20"
                >
                   {/* Outer Liquid Glass Container */}
                   <div className="relative p-[1px] rounded-[32px] overflow-hidden bg-gradient-to-br from-white/40 via-white/10 to-transparent shadow-[0_32px_64px_rgba(0,0,0,0.4),inset_0_2px_4px_rgba(255,255,255,0.2)] backdrop-blur-[24px]">
                      {/* Inner frosted content */}
                      <div className="bg-[#030712]/40 backdrop-blur-3xl rounded-[32px] p-2 flex flex-col gap-2 relative overflow-hidden border border-white/5">
                         {/* Beautiful subtle animated background glow */}
                         <div className="absolute -top-20 -right-20 w-40 h-40 bg-purple-500/20 blur-[50px] rounded-full animate-pulse" />
                         <div className="absolute -bottom-20 -left-20 w-40 h-40 bg-blue-500/20 blur-[50px] rounded-full animate-pulse" />
                         
                         {/* Hero Image Section */}
                         <div className="w-full h-[140px] sm:h-[160px] rounded-[28px] overflow-hidden relative border border-white/10 shadow-[0_4px_20px_rgba(0,0,0,0.3)] shrink-0 group">
                            <Image src="https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=2000&auto=format&fit=crop" className="absolute inset-0 w-full h-full object-cover group-hover:scale-110 transition-transform duration-1000" />
                            <div className="absolute inset-0 bg-gradient-to-t from-[#030712]/90 via-black/20 to-transparent" />
                            <div className="absolute bottom-4 left-5">
                               <h3 className="text-xl sm:text-2xl font-bold text-white tracking-tight leading-none mb-1 drop-shadow-md">Tokyo, Japan</h3>
                               <p className="text-[10px] sm:text-xs text-emerald-400 font-bold tracking-widest uppercase drop-shadow-md">Starts in 12 days</p>
                            </div>
                            <div className="absolute top-4 right-4 bg-black/40 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/20 flex items-center gap-1.5 shadow-lg">
                               <span className="relative flex h-2 w-2">
                                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                                  <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                               </span>
                               <span className="text-[9px] uppercase font-bold text-white/90 tracking-wider">Upcoming</span>
                            </div>
                         </div>
                         
                         {/* Bottom Info Section */}
                         <div className="px-5 py-3 relative z-10">
                            <div className="flex justify-between items-center relative z-10">
                               <div className="text-left">
                                 <span className="text-2xl sm:text-3xl font-black text-transparent bg-clip-text bg-gradient-to-b from-white to-white/60">SFO</span>
                                 <p className="text-[9px] sm:text-[10px] text-white/40 uppercase tracking-widest mt-0.5 font-bold">Outbound</p>
                               </div>
                               
                               <div className="flex-1 flex items-center justify-center relative px-4">
                                 <div className="absolute w-full border-t-[1.5px] border-dashed border-white/20 top-1/2 -translate-y-1/2" />
                                 <Plane className="w-5 h-5 sm:w-6 sm:h-6 text-purple-400 relative z-10 bg-[#030712] px-1 rounded-full transform rotate-45" />
                               </div>
                               
                               <div className="text-right">
                                 <span className="text-2xl sm:text-3xl font-black text-transparent bg-clip-text bg-gradient-to-b from-white to-white/60">HND</span>
                                 <p className="text-[9px] sm:text-[10px] text-white/40 uppercase tracking-widest mt-0.5 font-bold">Arrival</p>
                               </div>
                            </div>
                            
                            <Link to={ROUTES.TRIPS} className="relative z-10 mt-4 block">
                              <button className="w-full py-3.5 bg-gradient-to-r from-blue-500/20 to-purple-500/20 hover:from-blue-500/30 hover:to-purple-500/30 border border-white/10 rounded-2xl text-white text-sm font-bold transition-all duration-300 flex items-center justify-center gap-2 shadow-[inset_0_1px_2px_rgba(255,255,255,0.2)] group hover:scale-[1.02] active:scale-[0.98]">
                                View Itinerary <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                              </button>
                            </Link>
                         </div>
                      </div>
                   </div>
                </motion.div>
                
                '''
    content = content[:ticket_start] + new_ticket + content[ticket_end:]

with open('src/pages/HomePage.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Python script completed.")
