import { getTripImage } from '@/utils/imageUtils';

export const SLIDESHOW_IMAGES = [
  { url: getTripImage("Santorini GREECE"), city: "Santorini", country: "GREECE" },
  { url: getTripImage("Kyoto JAPAN"), city: "Kyoto", country: "JAPAN" },
  { url: getTripImage("Swiss Alps SWITZERLAND"), city: "Swiss Alps", country: "SWITZERLAND" },
  { url: getTripImage("Cinque Terre ITALY"), city: "Cinque Terre", country: "ITALY" },
  { url: getTripImage("Bora Bora FRENCH POLYNESIA"), city: "Bora Bora", country: "FRENCH POLYNESIA" },
  { url: getTripImage("Paris FRANCE"), city: "Paris", country: "FRANCE" },
  { url: getTripImage("Machu Picchu PERU"), city: "Machu Picchu", country: "PERU" },
  { url: getTripImage("Dubai UAE"), city: "Dubai", country: "UAE" },
  { url: getTripImage("New York City USA"), city: "New York City", country: "USA" },
  { url: getTripImage("London UK"), city: "London", country: "UK" },
  { url: getTripImage("Lake Tahoe USA"), city: "Lake Tahoe", country: "USA" },
  { url: getTripImage("Amsterdam NETHERLANDS"), city: "Amsterdam", country: "NETHERLANDS" },
  { url: getTripImage("Rome ITALY"), city: "Rome", country: "ITALY" },
  { url: getTripImage("Banff CANADA"), city: "Banff", country: "CANADA" },
  { url: getTripImage("Venice ITALY"), city: "Venice", country: "ITALY" },
  { url: getTripImage("Sydney AUSTRALIA"), city: "Sydney", country: "AUSTRALIA" },
  { url: getTripImage("Istanbul TURKEY"), city: "Istanbul", country: "TURKEY" },
  { url: getTripImage("Rio de Janeiro BRAZIL"), city: "Rio de Janeiro", country: "BRAZIL" },
  { url: getTripImage("Taj Mahal INDIA"), city: "Taj Mahal", country: "INDIA" },
  { url: getTripImage("Patagonia ARGENTINA"), city: "Patagonia", country: "ARGENTINA" },
  { url: getTripImage("Maldives MALDIVES"), city: "Maldives", country: "MALDIVES" },
  { url: getTripImage("Tokyo JAPAN"), city: "Tokyo", country: "JAPAN" },
  { url: getTripImage("Bali INDONESIA"), city: "Bali", country: "INDONESIA" },
  { url: getTripImage("Reykjavik ICELAND"), city: "Reykjavik", country: "ICELAND" },
  { url: getTripImage("Yellowstone USA"), city: "Yellowstone", country: "USA" },
  { url: getTripImage("Grand Canyon USA"), city: "Grand Canyon", country: "USA" },
  { url: getTripImage("Petra JORDAN"), city: "Petra", country: "JORDAN" }
];
