import { jsPDF } from 'jspdf';

export const generatePremiumPDF = async (trip) => {
  // A4 paper dimensions: 210 x 297 mm
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Helpers
  const margin = 20;
  let cursorY = margin;

  const destName = trip?.destination?.split('&')[0] || 'Unknown Destination';
  
  const formatDate = (dateStr) => {
    if (!dateStr) return 'TBD';
    return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(dateStr));
  };
  
  const startDateStr = formatDate(trip?.startDate);
  const endDateStr = formatDate(trip?.endDate);

  // --- HEADER SECTIONS ---
  
  // Top Dark Bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 50, 'F');

  // App Logo / Title (White)
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('VOYAGE GENIE', margin, 20);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175); // slate-400
  doc.text('OFFICIAL TRAVEL ITINERARY', margin, 26);

  // Big Destination Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.text(destName.toUpperCase(), margin, 40);

  cursorY = 65;

  // --- TRIP DETAILS GRID ---
  doc.setTextColor(31, 41, 55); // gray-800
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Trip Overview', margin, cursorY);
  
  cursorY += 8;

  // Details Box
  doc.setFillColor(243, 244, 246); // gray-100
  doc.roundedRect(margin, cursorY, pageWidth - (margin * 2), 25, 3, 3, 'F');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Dates:', margin + 5, cursorY + 10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${startDateStr} - ${endDateStr}`, margin + 25, cursorY + 10);

  doc.setFont('helvetica', 'bold');
  doc.text('Travelers:', margin + 100, cursorY + 10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${trip?.travelers || 2} People`, margin + 125, cursorY + 10);

  doc.setFont('helvetica', 'bold');
  doc.text('Budget:', margin + 5, cursorY + 18);
  doc.setFont('helvetica', 'normal');
  doc.text(`${trip?.currency || '$'} ${trip?.budget || 'N/A'}`, margin + 25, cursorY + 18);

  cursorY += 40;

  // --- MOCK ITINERARY SECTION ---
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Suggested Itinerary', margin, cursorY);
  
  cursorY += 10;

  const mockDays = [
    {
      title: 'Day 1: Arrival & Exploration',
      activities: [
        'Check-in to accommodation and rest.',
        `Take a walking tour around central ${destName}.`,
        'Welcome dinner at a highly-rated local restaurant.'
      ]
    },
    {
      title: 'Day 2: Culture & Landmarks',
      activities: [
        'Visit the primary historical landmarks.',
        'Lunch at a traditional cafe.',
        'Afternoon museum tour or cultural exhibition.',
        'Sunset views from a popular vantage point.'
      ]
    },
    {
      title: 'Day 3: Leisure & Departure',
      activities: [
        'Morning shopping at local markets for souvenirs.',
        'Relaxing brunch.',
        'Pack luggage and head to the airport/station.'
      ]
    }
  ];

  mockDays.forEach((day, index) => {
    if (cursorY > pageHeight - 40) {
      doc.addPage();
      cursorY = margin;
    }

    // Day Header
    doc.setFillColor(59, 130, 246); // blue-500
    doc.roundedRect(margin, cursorY - 4, 4, 4, 0.5, 0.5, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(day.title, margin + 8, cursorY);

    cursorY += 8;

    // Day Activities
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99); // gray-600
    
    day.activities.forEach((act) => {
      doc.text(`• ${act}`, margin + 5, cursorY);
      cursorY += 6;
    });

    cursorY += 5;
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Generated by Voyage Genie AI`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // Save the PDF
  const filename = `${destName.replace(/\s+/g, '_')}_Itinerary.pdf`;
  doc.save(filename);
};
